# group_vars/all.yml
# Variables visible to all nodes
---

rhbase_install_packages:
  - bash-completion
  - bind-utils
  - git
  - nano
  - tree
  - vim-enhanced
  - wget
rhbase_users:
  - name: kjell
    comment: 'kjell admin'
    groups:
      - users
      - wheel
    password: '$6$0xjjA9VH39Vm0STt$z.sDAJlxbSyWmQPl4VpQ8fjOGV2q2YCC29sjBUAMzHt/VjT9vYCroQDJUg8Y4VhZnrjm0HYCzZawtA37VO11V.'

rhbase_motd: true
rhbase_ssh_user: kjell
rhbase_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZPEMjMqykH4OO70pxRVDi9mNuSa2StnZM3PdMgeRhsKck9g3JNSovGft4smUcrb/VYDYaCYqOnmxm2tQNHHkg+RUEMEqE05Bh9IhKnnD+1qEsjNn+PUtu7kOGr2xHthQvzMO6kLTFrPHFNlTp9CvkhwwDAq4VRDNUa9N+QNyHpNWnIoupNxqfrDWSUXlzSAA4OVZOwKOwscgp/VjsDODNLqMkJoqkvg49/Nnq6XWoc9bQ1LSJRP9be1uGvY7zBF2vGVKEVT+G/s2JlAjyF/JikGlL/BXeLMOLnMhDeBX2r6ycsQ25zMGBlVtzSOzXhJLjstnUKUTki9inGgCfVVx/ Kjell@Kjell-Desktop



#  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1n+2DpDkTVTeDoWuH8Tag4rcFIkgE7Zc+MSFbB1EwBILpWTRFVURUwgyKmC+26gKJoBxkuYRJCgBN6nzOHpcXRFrBNy2sC36nkuzxaAy6Nlxao3JQ7DK8+C3UX7GfkZsPmj+Rq820k21mbMo8ET+qQENrd4xsjaMrobV2ZAhWkoFf1dYIzTlJj+x1MUlTlJmTizBTNEns46LemK58EZ/3ajuI0Kf4NudvNbIl7kwDAzuqlaZUiu/pgjOhc+22fzi/HTZm3WAVcMvTHm31SHETNJ/xNImalD37TW8PB9MKqFTMrq+rUXTdrXZ843TdaVVEloqo+H0WUZQfjFwvGOxT Kjell@Kjell-Desktop
#'
