# host_vars/pu001.yml
# Variables visible to pr001
---
rhbase_firewall_allow_services:
  - dhcp

dhcp_global_authoritative: authoritative
dhcp_global_default_lease_time: 43200
dhcp_global_domain_name: avalon.lan
dhcp_global_routers: 172.16.255.254
dhcp_global_domain_name_servers:
  - 172.16.255.254
dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'
  - name: reserved
    match: 'match if hardware = 1:00:11:22:33:44:55'

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    pools:
      - range_begin: 172.16.0.2
        range_end: 172.16.127.254
      - range_begin: 172.16.128.1
        range_end: 172.16.191.254
        allow: 'members of "reserved"'
      - range_begin: 172.16.192.1
        range_end: 172.16.255.253
        allow: 'members of "vbox"'



dhcp_hosts:
  - name: werkstation1
    mac: '00:11:22:33:44:55'
    ip: 172.16.128.15
