# host_vars/pu001.yml
# Variables visible to dns
---
rhbase_firewall_allow_services:
  - dns
#dnsmasq_domain: avalon.lan
#dnsmasq_authoritative: true
#dnsmasq_listen_address:
#  - 172.16.0.10
#dnsmasq_option_router: 172.16.255.254
