# host_vars/pr011.yml
# Variables visible to pr011
---
rhbase_firewall_allow_services:
  - samba
  - ftp
rhbase_user_groups:
  - students
  - teachers
  - it
  - public

rhbase_users:
  - name: kjell
    comment: 'kjell admin'
    groups:
      - wheel
      - it
      - public
    password: '$6$0xjjA9VH39Vm0STt$z.sDAJlxbSyWmQPl4VpQ8fjOGV2q2YCC29sjBUAMzHt/VjT9vYCroQDJUg8Y4VhZnrjm0HYCzZawtA37VO11V.'
  - name: docent
    comment: 'docent'
    groups:
      - public
      - teachers
    password: '$5$5Y0SjamA7UOfdIZ/$jSMWrseohxzERb62/a1rLyn9uUmWc.1sniX2oS2xGQA'
  - name: student
    comment: 'student'
    groups:
      - public
      - students
    password: '$5$P7FWl9GjMdxD.Wcu$LIZ.eH90JI1/LTB/FNC0YXgA0eXk.31ung7ZaMXnrS1'
    shell: /sbin/nologin
  - name: student2
    comment: 'student2'
    groups:
      - public
      - students
    password: '$5$P7FWl9GjMdxD.Wcu$LIZ.eH90JI1/LTB/FNC0YXgA0eXk.31ung7ZaMXnrS1'
    shell: /sbin/nologin
samba_users:
  - name: kjell
    password: test
  - name: docent
    password: teacher
  - name: student
    password: student
samba_shares:
  - name: HandIn
    comment: 'Share folder to hand in examinations'
    group: public
    valid_users: +students,+teachers,+it
    write_list: +students,+teachers,+it
    create_mode: '1775'
    force_create_mode: '1775'
    directory_mode: '1775'
    force_directory_mode : '1775'
  - name: ExaminationFiles
    comment: 'Share folder where students can find the exams'
    group: public
    valid_users: +students,+teachers,+it,+public
    write_list: +teachers
    create_mode: '0775'
    force_create_mode: '0775'
    directory_mode: '0775'
    force_directory_mode : '0775'

  - name: Teachers
    comment: 'Share folder for teachers, files with account info etc.'
    group: teachers
    valid_users: +teachers,+it
    write_list: +teachers,+it
    #directory_mode: '770'
samba_workgroup: avalon
samba_netbios_name: EXAMINATION
samba_load_homes: true
sambe_load_printers: false
vsftpd_anonymous_enable: false
vsftpd_local_enable: true
vsftpd_write_enable: true
vsftpd_local_umask: '007'
vsftpd_local_root: '/srv/shares/'
#elao_acl_files:
#    - name:        /srv/shares/ExaminationFiles
#      entity:      students
#      etype:       other
#      permissions: "rx"
#      state:       present
