# site.yml
---
- hosts: all
  become: true
  roles:
    - bertvv.rh-base

- hosts: dns
  become: true
  roles:
    - bertvv.bind

- hosts: dhcp
  become: true
  roles:
    - bertvv.dhcp

- hosts: samba
  become: true
  roles:
    - bertvv.samba
    - bertvv.vsftpd
  post_tasks:
    - name: management to sales
      acl:
        path: /srv/shares/sales
        entity: management
        etype: group
        permissions: rx
        state: present
    - name: management to it
      acl:
        path: /srv/shares/it
        entity: management
        etype: group
        permissions: rx
        state: present
