# site.yml
---
- hosts: all
  become: true
  roles:
    - bertvv.rh-base

- hosts: dns
  become: true
  roles:
  #  - bertvv.bind
    - bertvv.dnsmasq

- hosts: dhcp
  become: true
  roles:
    - bertvv.dhcp

- hosts: samba
  become: true
  roles:
    - bertvv.samba
    - bertvv.vsftpd
#    - elaoInfra.acl
  post_tasks:
    - name: teachers all access in ExaminationFiles
      acl:
        path: /srv/shares/ExaminationFiles
        entity: teachers
        etype: group
        permissions: rwx
        state: present
        default: yes
    - name: students read access in ExaminationFiles
      acl:
        path: /srv/shares/ExaminationFiles
        entity: students
        etype: group
        permissions: rx
        state: present
        default: yes
    - name: students prohibit access in Teachers folder
      acl:
        path: /srv/shares/Teachers
        entity: students
        etype: group
        permissions: ---
        state: present
        default: yes
#    - name: management to it
#      acl:
#        path: /srv/shares/it
#        entity: management
#        etype: group
#        permissions: rx
#        state: present
